name: Build on PR

on:
  pull_request:
    branches:
      - master

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest 
      - name: Install dependencies
        run: bun install
      
      - name: Check formatting
        run: bun run check-format

      - name: Run build
        run: bun run build
